/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class currencyConverter extends javax.swing.JFrame {

    /**
     * Creates new form currencyConverter
     */
    public currencyConverter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        left_panel = new javax.swing.JPanel();
        converter_title = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        currency_title = new javax.swing.JLabel();
        left_bottom_panel = new javax.swing.JPanel();
        copyright = new javax.swing.JLabel();
        right_panel = new javax.swing.JPanel();
        from = new javax.swing.JLabel();
        to = new javax.swing.JLabel();
        amount = new javax.swing.JLabel();
        amount_box = new javax.swing.JTextField();
        convert_button = new javax.swing.JButton();
        reset_button = new javax.swing.JButton();
        from_box1 = new javax.swing.JComboBox<>();
        from_box2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Currency Converter");
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setForeground(new java.awt.Color(255, 255, 255));

        left_panel.setBackground(new java.awt.Color(102, 204, 255));
        left_panel.setForeground(new java.awt.Color(0, 153, 255));

        converter_title.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        converter_title.setForeground(new java.awt.Color(255, 255, 255));
        converter_title.setText("CONVERTER");
        converter_title.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_us_dollar_40px.png"))); // NOI18N

        currency_title.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        currency_title.setForeground(new java.awt.Color(255, 255, 255));
        currency_title.setText("CURRENCY");
        currency_title.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        left_bottom_panel.setBackground(new java.awt.Color(204, 204, 204));

        copyright.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        copyright.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_copyright_16px.png"))); // NOI18N
        copyright.setText("Copyright Kel6 2021. All Rights Reserved.");

        javax.swing.GroupLayout left_bottom_panelLayout = new javax.swing.GroupLayout(left_bottom_panel);
        left_bottom_panel.setLayout(left_bottom_panelLayout);
        left_bottom_panelLayout.setHorizontalGroup(
            left_bottom_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, left_bottom_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(copyright)
                .addGap(25, 25, 25))
        );
        left_bottom_panelLayout.setVerticalGroup(
            left_bottom_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(copyright, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout left_panelLayout = new javax.swing.GroupLayout(left_panel);
        left_panel.setLayout(left_panelLayout);
        left_panelLayout.setHorizontalGroup(
            left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(left_panelLayout.createSequentialGroup()
                .addGroup(left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(left_panelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(currency_title, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(converter_title, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(left_bottom_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        left_panelLayout.setVerticalGroup(
            left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(left_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(left_panelLayout.createSequentialGroup()
                        .addComponent(currency_title, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(converter_title, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(163, 163, 163)
                .addComponent(left_bottom_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        right_panel.setBackground(new java.awt.Color(255, 255, 255));
        right_panel.setForeground(new java.awt.Color(255, 255, 255));

        from.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        from.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        from.setText("From");

        to.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        to.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        to.setText("To");

        amount.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        amount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        amount.setText("Amount");

        amount_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amount_boxActionPerformed(evt);
            }
        });

        convert_button.setBackground(new java.awt.Color(102, 204, 255));
        convert_button.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        convert_button.setForeground(new java.awt.Color(255, 255, 255));
        convert_button.setText("Convert");
        convert_button.setBorder(null);
        convert_button.setBorderPainted(false);
        convert_button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        convert_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        convert_button.setVerticalTextPosition(javax.swing.SwingConstants.CENTER);
        convert_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convert_buttonActionPerformed(evt);
            }
        });

        reset_button.setBackground(new java.awt.Color(102, 204, 255));
        reset_button.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        reset_button.setForeground(new java.awt.Color(255, 255, 255));
        reset_button.setText("Reset");
        reset_button.setBorder(null);
        reset_button.setBorderPainted(false);
        reset_button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        reset_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reset_button.setVerticalTextPosition(javax.swing.SwingConstants.CENTER);
        reset_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_buttonActionPerformed(evt);
            }
        });

        from_box1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        from_box1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "US$ USD", "C$ CAD", "€ EUR", "¥ CNY", "¥ JPY", "£ GBP" }));
        from_box1.setBorder(null);
        from_box1.setBackground(new java.awt.Color(255, 255, 255));
        from_box1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                from_box1ActionPerformed(evt);
            }
        });

        from_box2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        from_box2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "US$ USD", "C$ CAD", "€ EUR", "¥ CNY", "¥ JPY", "£ GBP" }));
        from_box2.setBackground(new java.awt.Color(255, 255, 255));
        from_box2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                from_box2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout right_panelLayout = new javax.swing.GroupLayout(right_panel);
        right_panel.setLayout(right_panelLayout);
        right_panelLayout.setHorizontalGroup(
            right_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(right_panelLayout.createSequentialGroup()
                .addGroup(right_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(to, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(right_panelLayout.createSequentialGroup()
                .addGroup(right_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(right_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(from, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(right_panelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(right_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, right_panelLayout.createSequentialGroup()
                                .addComponent(convert_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(reset_button, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(right_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(from_box1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(amount_box, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(from_box2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        right_panelLayout.setVerticalGroup(
            right_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(right_panelLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(amount_box, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(from, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(from_box1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(to, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(from_box2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(right_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(convert_button, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reset_button, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(left_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 292, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(right_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(609, 609, 609))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(right_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(left_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void from_box2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_from_box2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_from_box2ActionPerformed

    private void from_box1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_from_box1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_from_box1ActionPerformed

    private void reset_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reset_buttonActionPerformed

    private void convert_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convert_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_convert_buttonActionPerformed

    private void amount_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amount_boxActionPerformed
        int bilangan1 = (Integer.parseInt(amount_box.getText().trim()));
    }//GEN-LAST:event_amount_boxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(currencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(currencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(currencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(currencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new currencyConverter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amount;
    private javax.swing.JTextField amount_box;
    private javax.swing.JPanel background;
    private javax.swing.JButton convert_button;
    private javax.swing.JButton reset_button;
    private javax.swing.JLabel converter_title;
    private javax.swing.JLabel copyright;
    private javax.swing.JLabel currency_title;
    private javax.swing.JLabel from;
    private javax.swing.JComboBox<String> from_box1;
    private javax.swing.JComboBox<String> from_box2;
    private javax.swing.JPanel left_bottom_panel;
    private javax.swing.JPanel left_panel;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel right_panel;
    private javax.swing.JLabel to;
    // End of variables declaration//GEN-END:variables
}
